### ISSUE TITLE
ValidatorImpl removes resources from the model that have sh:path's on them

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.validation#23]
VI class uses the following snippet of code:

            model.add(resource.listProperties());

            validationResult = validateInternal(model, shapeModel);
            if (validationResult.isValid()) {
                isValid = true;
            }

I suspect it has caused problems described in https://github.com/labra/shaclex/issues/118

@yashkhatri could you please check this?

**Comment by berezovskyi** [comment]
In other words, you seem to be "isolating" each resource in an individual model and the following may fail:

```turtle
_:p1  a  family:Person ;
	family:name  "Ricardo" ;
	family:friend <p2> .

<p2> a family:Person ;
	family:name  "Javier" .
```

**Comment by yashkhatri** [comment]
@berezovskyi The code for ValidatorImpl has changed a lot after [#38](https://github.com/labra/shaclex/issues/38) 

To answer your concern, the `getValidationsMethod(Model dataModel, Model shapeModel)` method is now changed. Previously, the resources were isolated into individual model and then validated. This was done because the underlying shaclex library used to stop and return the first error found in the model. We want all the errors to be returned. Hence, the blank nodes were also ignored in this case.

Now, after the fix in the underlying shaclex library, it is returning all the errors and hence, there's no need to isolate the resources in individual model.

See [this]( https://github.com/eclipse/lyo.validation/pull/14/files#diff-ecb5f1cb1c7452bb0377ab9da1901e12R88) method.

Please try this in the latest version of Lyo.Validation by pulling [shaclex-0.0.76](https://github.com/eclipse/lyo.validation/tree/shaclex-0.0.76) branch.

**Comment by berezovskyi** [comment]
@neormx please test

**Comment by neormx** [comment]
Yes, it worked as expected. Any idea when this PR could be merged/released?

BTW, I needed to change these lines in test packages in order to compile https://github.com/eclipse/lyo.validation/blob/44eb36cbe782370dd139930e297e5596c67bf61d/src/test/java/org/eclipse/lyo/validation/AResource.java#L118 and https://github.com/eclipse/lyo.validation/blob/44eb36cbe782370dd139930e297e5596c67bf61d/src/test/java/org/eclipse/lyo/validation/AResource.java#L166

The change was to
```
@ShaclDataType(DataType.Integer)
```

**Comment by yashkhatri** [comment]
@neormx Yes, thanks for letting us know. This might be missed when refactoring. I will update this.

**Comment by yashkhatri** [comment]
I am leaving this issue open until the [PR ](https://github.com/eclipse/lyo.validation/pull/14) is merged in master.

**Comment by yashkhatri** [comment]
[PR](https://github.com/eclipse/lyo.validation/pull/14) is now merged in master. Hence, closing this issue.
